### ISSUE TITLE
vessel.thrust doesn't account for thrust limiter

### ISSUE THREAD

**Issue by borogove** [djungelorm/krpc#103]
If thrust limiter is below 100% on an engine, vessel.thrust continues to report the vessel's 100% thrust. The only way to get true thrust would be to walk the part tree and inspect the limiter. I don't know off the top of my head if 50% throttle and 50% thrust limiter is 50% of normal max thrust or 25% of normal; that might determine whether this is a bug :) (i.e. is thrust limiter a cap on throttle or a multiplier in series with throttle?)

**Comment by djungelorm** [comment]
The thrust limiter is in series with the throttle, so the thrust for each engine is calculated as
```engine_max_thrust * engine_throttle_limit * main_throttle```
So it would be 25% in your example.

This is definitely a bug and a bit of a mess in general... For example Vessel.Thrust should do a similar thing to Engine.Thrust for consistency.

I'll update the vessel class so that:
 * Vessel.Thrust - gets the current thrust the vessel is producing (takes main throttle and engine limiter into account)
 * Vessel.MaxThrust - gets the maximum thrust the vessel can produce (when main throttle is 100% but respecting each engines throttle limit)

And I'll update the engine class similarly:
 * Engine.Thrust - gets the current thrust of the engine (taking main throttle and engine limiter into account)
 * Engine.MaxThrust - gets the thrust when throttle is 100% (but respecting the throttle limit)

**Comment by djungelorm** [comment]
...or maybe do something similar to kOS https://github.com/KSP-KOS/KOS/issues/234
and have MaxThrust (ignores limiter) and AvailableThrust (includes limiter)
