### ISSUE TITLE
Flight/orbital velocity/speed return zero through Python

### ISSUE THREAD

**Issue by NOTtheMessiah** [djungelorm/krpc#185]
when I
```python
flight = vessel.flight()
print flight.velocity
print flight.speed
print vessel.orbit.speed
```

I get
```
(0.0, 0.0, 0.0)
0.0
0.0
```
on kRPC v0.1.12 installed through CKAN and python package through pip for python2

a search yields a similar issue: https://github.com/djungelorm/krpc/issues/149

**Comment by djungelorm** [comment]
You're getting zeroes because vessel.flight() returns values in the vessel's "surface reference frame". This reference frame moves with the vessel, hence the zeroes.

Try using a different reference frame, for example to get orbital velocities and speeds. For example, see these tutorials:

http://djungelorm.github.io/krpc/docs/tutorials/reference-frames.html#orbital-speed

**Comment by Maxwell9000** [comment]
>  djungelorm commented on 4 Jan 2016 
[...]http://djungelorm.github.io/krpc/docs/tutorials/reference-frames.html#orbital-speed

The link is dead. Please provide information here again so people who search for the issue
will find it. Sadly this issue isn't described in the documentation :(
