### ISSUE TITLE
Ability to control arbitrary vessels, not just the active one

### ISSUE THREAD

**Issue by djungelorm** [djungelorm/krpc#61]
Control and AutoPilot classes should be able to be used for vessels other than the active vessel.

I think the vessel will need to be within physics range for this to work.

**Comment by finger563** [comment]
I would like to help with this issue, as it is required for a research project of mine.  KSP supports this, yes?

**Comment by djungelorm** [comment]
Yes it's possible, for vessel's within physics range of the active vessel. I have an implementation for this I'm currently testing and will release very soon!

**Comment by finger563** [comment]
I know mods can alter the range of physics to increase it if desired, perhaps there could be an additional interface for this?

William Emfinger 
Graduate research assistant 
Vanderbilt university institute for software integrated systems 
16th avenue s Nashville TN 37212

**Comment by djungelorm** [comment]
I think changing the physics distance is a bit out of scope for this mod, so would prefer to leave it out (for now at least!)

**Comment by finger563** [comment]
Hmmm, I've been looking through Baha's source because his mod has the ability to change the load/unload ranges (i.e. physics ranges) and have found relevant code here:

[BD_Armory](https://github.com/BahamutoD/BDArmory/blob/master/BahaTurret/BDArmorySettings.cs#L618)

From forum posts, it seems like this may have some bugs, but it at least is a step in the right direction.  Similarly, principia modifies all objects' properties (position/velocity/etc.) according to n-body physics including altering planet orbits.

[principia](https://github.com/mockingbirdnest/Principia)

Unfortunately it would probably not have the proper effects for doing full physics calculations (e.g. collision detection and resolution), but perhaps in the future and after the upgrade to PhysX 3.5 which will come with the conclusion of the upgrade to unity 5?

**Comment by djungelorm** [comment]
This is a bit off topic for this issue. I've added a separate issue here for discussion: #145

This functionality would certainly be useful, but it's the sort of "non-stock" functionality I'd like to keep out of the SpaceCenter service. Could certainly be added to a new, separate service though, maybe called DebugTools? In a similar vein to the [TestingTools](https://github.com/djungelorm/krpc/blob/master/test/TestingTools/KRPCService.cs) service that I use to run my unit tests (such as setting the orbit of a craft, similarly to how HyperEdit works).

**Comment by finger563** [comment]
how close is this feature to being somewhat/fully functional?

**Comment by djungelorm** [comment]
It's functional, but needs testing. I've added a pre-release of these changes here if you want to try it out: https://github.com/djungelorm/krpc/releases/tag/v0.1.10-pre-controls
