### ISSUE TITLE
Improve reference frames

### ISSUE THREAD

**Issue by djungelorm** [djungelorm/krpc#66]
On branch feature/refactor-reference-frames

Details of API changes here: https://github.com/djungelorm/krpc/wiki/SpaceCenter-Service-Changes-in-0.1.4

**Comment by rallen10** [comment]
I really appreciate all the work that was done on kRPC but I have to point out a detail that I find absolutely baffling. Did you all actually settle on a left-handed reference frame?! Is [this image](https://krpc.github.io/krpc/tutorials/reference-frames.html#vessel-orbital-reference-frame) correct?

**Comment by yehoodig** [comment]
That’s not krpc, that’s a feature of the game.  Nothing they could do about it.

**Comment by rallen10** [comment]
@yehoodig fair enough. I don't know if anyone maintains the documentation but it might be worth explicitly calling out the left-handed convention in the [reference frame documents](https://krpc.github.io/krpc/tutorials/reference-frames.html#vessel-orbital-reference-frame). Even with the detailed description of x, y, z axes for each reference frame, it only just dawned on me after a few weeks of using kRPC that they are left-handed. I didn't even think to check because I've never seen a left-handed reference frame in the wild before.

**Comment by rallen10** [comment]
@yehoodig I just made a comment that the documentation should note that the reference frames are left handed, but then I saw that has already been done so I deleted the comment.

Coming from an aerospace background, this is the first time I've seen a left-handed frame in the wild.

**Comment by yehoodig** [comment]
I’ve been to enough fairs myself.

If you look into it, it’s the standard in computer simulation.  CAD/CAM, etc.  don’t ask me why.  I certainly understand your reaction, though.
